-- AlterTable
ALTER TABLE "Event" ADD COLUMN "ticketUrl" TEXT;
ALTER TABLE "Event" ADD COLUMN "price" TEXT;
ALTER TABLE "Event" ADD COLUMN "tags" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Event" ADD COLUMN "isFeatured" BOOLEAN NOT NULL DEFAULT false;
